episodes:
    length: 20  # minutes
    syncTimer: true  # if true, the timer will be synchronized with a clock to avoid having long episodes because of lag

map:
    size: 2000
    wall:
        height: 128
        block: BEDROCK

daylightCycle:
    do: false
    time: 6000  # Initial time (or game time if the daylight cycle is disabled) in ticks. 6000 = noon.

scoreboard: Kill the Patrick

kick-on-death:
    kick: true
    time: 30
    allow-reconnect: true

death-messages:
    notifyIfTeamHasFallen: true
    deathMessagesPrefix: "ยง6"  # Use this to increase visibility of death messages.
    teamDeathMessagesPrefix: "ยง6"

# If true, the name of the players will be colorized according to the teams.
colorizeChat: true

gameplay-changes:
    weather: true
    
    replaceGhastTearsWithGold: true
    craftGoldenMelonWithGoldBlock: true
    
    craftGoldenAppleFromHead:
        do: 
            fromHuman: true
            fromWither: true
        craftNotchApple: false
        addLore: true
        numberCrafted:
            fromPlayer: 3
            fromWither: 1
    
    
    disableEnderpearlsDamages: true
    
    # If true a compass will show the nearest player, and the craft will be different.
    # Else, the craft will be standard and the compass will show the spawn point of the team/player (not the world spawn point).
    compass: true

slow-start:
    delayBetweenTP: 3  # in seconds

# Use this to set the spawnpoints of the teams (or the players)
# You can also use the command /uh addspawn (see /uh for documentation) to add temporary spawn points.
# (The spawn points added through /uh addspawn are deleted when the server is stopped.)
#
# Format:
#     - x,z
#     - x,z
#     - etc.

spawnpoints:
    -

# Use this to pre-register the teams.
# Format:
#     - color
#  -- OR --
#     - color,name

teams:
    -
